version: '3.8'
services:
  mysql_slow_query:
    container_name: 'mysql_slow_query'
    build:
      context: .
      args:
          UID: ${UID}
          GID: ${GID}
    volumes:
      - ${LOG_PATH}:${LOG_PATH}:ro
      - ${LAST_FILE_POSITION}:/usr/src/app/lfp_data:rw
    restart: unless-stopped
